name: day_night_digital_clock
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: DS-DIGII
      fonts:
        - asset: third_party/DS-DIGII.TTF
    - family: Night
      fonts:
        - asset: third_party/night.ttf
  assets:
    - assets/day.jpg
    - assets/nighty.jpg

